# Generated by Django 4.0.3 on 2022-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_voterlist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
