# Generated by Django 4.0.3 on 2022-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_voterlist_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='elec_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('vote', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
