# Generated by Django 4.0.3 on 2022-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_elec_res_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daseignation', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='image/team')),
            ],
        ),
    ]
