# Generated by Django 4.0.3 on 2022-08-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_my_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_team',
            old_name='daseignation',
            new_name='designation',
        ),
    ]
