# Generated by Django 4.0.3 on 2022-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('bimage', models.ImageField(upload_to='image/blog/')),
            ],
        ),
    ]
