# Generated by Django 4.0.3 on 2022-08-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_name_contact_fname_contact_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lname',
        ),
    ]
